import Link from 'next/link';
import { SimulateButton } from '@/components/action-buttons';
import { Badge, Card } from '@/components/status';
import { getWorkspaceData } from '@/lib/data';

export default async function SimulationPage() {
  const data = await getWorkspaceData();
  return (
    <div>
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end">
        <div>
          <h1 className="text-4xl font-semibold tracking-tight">Runtime Tests</h1>
          <p className="mt-3 max-w-3xl text-white/60">Test the generated OS by running workflows. Optional runtime events are generated by Bedrock from your actual agents, workflows, policies, and results.</p>
        </div>
        <div className="flex flex-wrap gap-3">
          <Link href="/dashboard/workflows" className="rounded-xl bg-white px-4 py-2 text-sm font-medium text-black">Run workflow</Link>
          <SimulateButton />
        </div>
      </div>

      <div className="mt-8 grid gap-5 lg:grid-cols-2">
        <Card>
          <h2 className="text-xl font-semibold">Workflow test runs</h2>
          <div className="mt-5 space-y-3">
            {data.workflowRuns.map((run) => {
              const workflow = data.workflows.find((item) => item.id === run.workflowId);
              return (
                <div key={run.id} className="rounded-lg border border-white/10 bg-black/25 p-4">
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <h3 className="font-medium">{workflow?.name || 'Workflow run'}</h3>
                      <p className="mt-1 text-sm text-white/45">{run.resultSummary}</p>
                    </div>
                    <Badge value={run.status} />
                  </div>
                </div>
              );
            })}
            {!data.workflowRuns.length && <p className="text-sm text-white/45">No workflow tests yet. Open Workflows and run one for result.</p>}
          </div>
        </Card>

        <Card>
          <h2 className="text-xl font-semibold">Generated runtime events</h2>
          <div className="mt-5 space-y-3">
            {data.events.map((event) => {
              const agent = data.agents.find((item) => item.id === event.agentId);
              return (
                <div key={event.id} className="rounded-lg border border-white/10 bg-black/25 p-4">
                  <div className="flex items-start justify-between gap-4">
                    <div>
                      <h3 className="font-medium">{event.title}</h3>
                      <p className="mt-1 text-sm text-white/45">{agent?.name || 'System event'}</p>
                    </div>
                    <Badge value={event.status} />
                  </div>
                  <p className="mt-4 text-white/60">{event.description}</p>
                  <div className="mt-4 flex gap-2"><Badge value={event.severity} /><Badge value={event.eventType} /></div>
                </div>
              );
            })}
            {!data.events.length && <p className="text-sm text-white/45">No runtime events generated yet.</p>}
          </div>
        </Card>
      </div>
    </div>
  );
}
